default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV['DB_PASSWORD'] %>
  port: <%= ENV['DB_PORT'] %>
  host: <%= ENV['DB_HOST'] %>

development:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>_development

production:
  <<: *default
  database: <%= ENV['DB_DATABASE'] %>
